spring:
  application:
    name: MokokoMarket
  profiles:
    active: dev

---


spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-mrlfp-kr.vpc-pub-cdb.ntruss.com:3306/mokoko-market?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: test
    password: "!@test1234"

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: Smcbfw_WXTXz1O5VFd2N
            client-secret: y7zyxyxeMD
            scope:
              - name
              - email
              - profile_image
              - phone
            client-name: Naver
            authorization-grant-type: authorization_code # authorization-grant type
            redirect-uri: http://localhost:8080/login/oauth2/code/naver # redirect - uri
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    com:
      zaxxer: INFO
    org:
      springframework:
        security: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: debug