spring:
  application:
    name: MokokoMarket
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-mrlfp-kr.vpc-pub-cdb.ntruss.com:3306/test?serverTimezone=Asia/Seoul
    username: mokoko-market
    password: "!@test1234"
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL
#    username: sa
#    password:

#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-id: ${NAVER_DEV_APP_CLIENT_ID}
#            client-secret: ${NAVER_DEV_APP_CLIENT_SECRET}
#            scope:
#              - name
#              - email
#              - profile_image
#              - gender
#            client-name: Naver
#            authorization-grant-type: authorization_code # authorization-grant type
#            redirect-uri: ${OAUTH2_NAVER_REDIRECT_URI} # redirect - uri
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response

  h2:
    console:
      enabled: true

logging:
  level:
    com:
      zaxxer: INFO
    org:
      springframework:
        security: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: debug