name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dodobird99/mokoko-market-backend:latest

      - name: Build Frontend Image
        uses: docker/build-push-action@v2
        with:
          context: ./src/main/mokokofront
          push: true
          tags: dodobird99/mokoko-market-frontend:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          timeout: 300s
          debug: true
          script: |
            docker pull dodobird99/mokoko-market-backend:latest
            docker pull dodobird99/mokoko-market-frontend:latest
            
            docker stop mokoko-market-backend || true
            docker rm mokoko-market-backend || true
            
            docker stop mokoko-market-frontend || true
            docker rm mokoko-market-frontend || true
            
            docker run -d --name mokoko-market-backend -p 8080:8080 dodobird99/mokoko-market-backend:latest
            docker run -d --name mokoko-market-frontend -p 80:3000 dodobird99/mokoko-market-frontend:latest